/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-01 08:37:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/nahyun.shin/web_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/exam-spring-master/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1755754927504L));
    _jspx_dependants.put("/static/common/common.jsp", Long.valueOf(1756370946000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel =\"stylesheet\" href=\"/webjars/bootstrap/5.3.1/css/bootstrap.min.css\"/>\n");
      out.write("\n");
      out.write("<script src=\"/webjars/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"/webjars/bootstrap/5.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("	function  makeTD(className,  contents){\n");
      out.write("		   const td = $('<td></td>');\n");
      out.write("		   td.addClass(className);\n");
      out.write("		   td.append(contents);\n");
      out.write("		   \n");
      out.write("		   return td;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("        *{\n");
      out.write("            padding: 0;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body{\n");
      out.write("            background-color: #b4b3b3;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .container{\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .contents{\n");
      out.write("            width: 400px;\n");
      out.write("            height: 300px;\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 1px 1px 4px 4px #e9e9e9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-form{\n");
      out.write("            display: flex;\n");
      out.write("            height :100%;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .ip-txt{\n");
      out.write("            width: 250px;\n");
      out.write("            height: 34px;\n");
      out.write("            border: none;\n");
      out.write("            border-bottom: 2px solid black;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .mb-4 {\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .ip-txt:focus{\n");
      out.write("            border-bottom-color: #007bff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .title{\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn{\n");
      out.write("               width: 95px;\n");
      out.write("               height: 35px;\n");
      out.write("               background-color: white;\n");
      out.write("               border: none;\n");
      out.write("               border-radius: 5px;\n");
      out.write("               color: white;\n");
      out.write("               font-weight: 500;\n");
      out.write("               font-size: 16px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        \n");
      out.write("        .btn-primary{\n");
      out.write("               background-color: #007bff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("          .btn-success{\n");
      out.write("               background-color: #03a51e;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <main class=\"container\">\n");
      out.write("        <section class=\"contents\">         \n");
      out.write("             <div class=\"login-form\">\n");
      out.write("              <header class=\"title\">\n");
      out.write("                 <h2> Login</h2>\n");
      out.write("             </header>\n");
      out.write("                <div class=\"mb-4\">\n");
      out.write("                    <input type=\"text\" class=\"ip-txt\" id=\"userId\" placeholder=\"ID\">\n");
      out.write("                </div>\n");
      out.write("                 <div  class=\"mb-4\">\n");
      out.write("                    <input type=\"password\" class=\"ip-txt\" id=\"passwd\" placeholder=\"PASSWORD\">\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <button class=\"btn btn-primary\" onclick=\"login();\">로그인</button>\n");
      out.write("                     <button class=\"btn btn-success\" onclick=\"goJoin();\">회원 가입</button>\n");
      out.write("                </div>\n");
      out.write("             </div>\n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("    function validated() {\n");
      out.write("        const userId =  document.querySelector('#userId');\n");
      out.write("        const passwd = document.querySelector('#passwd');\n");
      out.write("\n");
      out.write("        var regex = /^(?=.*[a-zA-Z])(?=.*[!@#$%^&*()])[a-zA-Z\\d!@#$%^&*()]{8,12}$/;\n");
      out.write("\n");
      out.write("        if(userId.value.trim().length === 0) {\n");
      out.write("            alert('아이디를 입력하십시오.');\n");
      out.write("            userId.focus();\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("         if(passwd.value.trim().length === 0) {\n");
      out.write("            alert('패스워드를 입력하십시오.');\n");
      out.write("            passwd.focus();\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("       /*  if(!regex.test(passwd.value)){\n");
      out.write("            alert('패스워드는 최소 8자리 이상이며, 대소문자와 특수기호를 포함해야합니다.');\n");
      out.write("            return false;\n");
      out.write("        } */\n");
      out.write("\n");
      out.write("        return true;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("    const login = () =>{\n");
      out.write("\n");
      out.write("        if( validated() ) {\n");
      out.write("            //ajax 를 통해서 비동기로 서버에 로그인 확인\n");
      out.write("            $.ajax({\n");
      out.write("            	url : '/user/login.do',\n");
      out.write("            	type :'post',\n");
      out.write("            	dataType : 'json',\n");
      out.write("            	data : {\n");
      out.write("            		userId : $('#userId').val(),\n");
      out.write("            		passwd : $('#passwd').val()\n");
      out.write("            	}\n");
      out.write("            }).done(function(res){\n");
      out.write("            	\n");
      out.write("            	if(res.resultCode === 200) {\n");
      out.write("            		location.href = \"/bank/list.do\";\n");
      out.write("            	}else {\n");
      out.write("            		alert('아이디 나 패스워드를 확인해주십시오.');\n");
      out.write("            		return false;\n");
      out.write("            	}\n");
      out.write("            	\n");
      out.write("            }).fail(function(xhr, status, error){\n");
      out.write("            	alert(\"로그인 에러!!\");\n");
      out.write("            })\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    const goJoin=()=>{\n");
      out.write("    	location.href ='/user/join.do';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
