/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-29 06:41:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1755754927504L));
    _jspx_dependants.put("jar:file:/C:/nahyun.shin/web_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/spring-master/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/static/common/common.jsp", Long.valueOf(1756370946000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>사용자가입</title>\r\n");
      out.write("    ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel =\"stylesheet\" href=\"/webjars/bootstrap/5.3.1/css/bootstrap.min.css\"/>\n");
      out.write("\n");
      out.write("<script src=\"/webjars/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"/webjars/bootstrap/5.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("	function  makeTD(className,  contents){\n");
      out.write("		   const td = $('<td></td>');\n");
      out.write("		   td.addClass(className);\n");
      out.write("		   td.append(contents);\n");
      out.write("		   \n");
      out.write("		   return td;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            background-color: #f5f3f3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .join-box {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            background-color:  #ffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <main class=\"container d-flex justify-content-center align-items-center vh-100\">\r\n");
      out.write("        <div class=\"card shadow p-4 join-box\">\r\n");
      out.write("            <header>\r\n");
      out.write("                <h2 class=\"mt-4 text-center\">회원가입</h2>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div>\r\n");
      out.write("            <form >\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"userId\" class=\"form-label\">아이디</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userId\" name=\"userId\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"userName\" class=\"form-label\">이름</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"userName\" name=\"userName\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"passwd\" class=\"form-label\">패스워드</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"passwd\" name=\"passwd\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"passwdConfirm\" class=\"form-label\">패스워드 확인</label>\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"passwdConfirm\" name=\"passwdConfirm\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"birth\" class=\"form-label\">생년월일</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"birth\" name=\"birth\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                     <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"phone\" class=\"form-label\">모바일</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"email\" class=\"form-label\">이메일</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("                </div>           \r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"text-center\">\r\n");
      out.write("                <button type=\"button\" id=\"joinBtn\" class=\"btn btn-primary me-2\">가입</button>\r\n");
      out.write("                <button type=\"button\" id=\"cancelBtn\" class=\"btn btn-secondary\">취소</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </main>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\" ></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  const searchAddr = ()=>{\r\n");
      out.write("    new daum.Postcode(\r\n");
      out.write("        {\r\n");
      out.write("            oncomplete :function(data){\r\n");
      out.write("                let fullAddr = '';\r\n");
      out.write("                let extarAddr = '';\r\n");
      out.write("\r\n");
      out.write("                //도로명 주소 선택 여부\r\n");
      out.write("                if(data.userSelectedType === 'R') {\r\n");
      out.write("                    fullAddr = data.roadAddress;\r\n");
      out.write("                }else {\r\n");
      out.write("                      fullAddr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                //법정동    \r\n");
      out.write("                if(data.bname.trim().length > 0 ||  /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                    extarAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                //아파트 또는 빌딩 명\r\n");
      out.write("                if(data.buildingName.trim().length > 0){\r\n");
      out.write("                    extarAddr +=  (extarAddr.length > 0 ? ', ' : '') +  data.buildingName;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                extarAddr =  extarAddr.length > 0 ?  ` ( ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${extarAddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" )` : extarAddr;\r\n");
      out.write("                fullAddr += extarAddr;\r\n");
      out.write("\r\n");
      out.write("               // $('#addr').val(fullAddr);\r\n");
      out.write("               document.querySelector('#addr').value =  fullAddr;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    ).open();\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function validated() {\r\n");
      out.write("    // 미 입력 시 노출 될 메시지\r\n");
      out.write("    // key 는 input 창의 id와 동일하게 한다. \r\n");
      out.write("    const eventMessages = {\r\n");
      out.write("        userId : '아이디를 입력하십시오',\r\n");
      out.write("        userName : '이름을 입력하십시오.',\r\n");
      out.write("        passwd : '패스워드를 입력하십시오',\r\n");
      out.write("        passwdConfirm : '패스워드 확인을 입력하십시오',\r\n");
      out.write("        birth : '생년월일을 입력하십시오',\r\n");
      out.write("        phone :'주민번호를 입력하십시오',\r\n");
      out.write("        email : '메일을 입력하십시오'\r\n");
      out.write("    }  \r\n");
      out.write("\r\n");
      out.write("    /*\r\n");
      out.write("       자바스크립트 object 에서 값을 가져오거나 주는 법\r\n");
      out.write("       obj[key],  obj[key]= value;\r\n");
      out.write("       obj.key ,  obj.key = value;\r\n");
      out.write("    */\r\n");
      out.write("\r\n");
      out.write("    //addrDetail 빼고 모든 input 엘리먼트 가져오기 \r\n");
      out.write("    const inputArr = $('input[type=\"text\"]:not(#addrDetail), input[type=\"password\"]');\r\n");
      out.write("\r\n");
      out.write("    //인증용 변수\r\n");
      out.write("    let isConfirm = true;\r\n");
      out.write("    //메시지 담을 변수 \r\n");
      out.write("    let alertMessage = '';\r\n");
      out.write("\r\n");
      out.write("    $.each(inputArr, (index, eleObj)=>{\r\n");
      out.write("        // 콜백에서 사용되는 객체는 자바스크립트 객체임을!!\r\n");
      out.write("        const id = eleObj.id;\r\n");
      out.write("        const value = eleObj.value.trim();\r\n");
      out.write("        //입력 값이 없을 경우 \r\n");
      out.write("        if(value.length === 0) {\r\n");
      out.write("            isConfirm = false;\r\n");
      out.write("            alertMessage =  eventMessages[id];\r\n");
      out.write("            $('#'+id).focus(); // 입력란에 포커스 주기 \r\n");
      out.write("            return false; //break;\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //입력 값이 없을 경우\r\n");
      out.write("    if(!isConfirm) {\r\n");
      out.write("        alert(alertMessage);\r\n");
      out.write("        return isConfirm;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //유효성 통과\r\n");
      out.write("    return isConfirm;\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  const goJoin = (e)=>{\r\n");
      out.write("    if(validated()) {\r\n");
      out.write("    	\r\n");
      out.write("    	const param = {\r\n");
      out.write("    	        userId : $('#userId').val(),\r\n");
      out.write("    	        userName : $('#userName').val(),\r\n");
      out.write("    	        passwd : $('#passwd').val(),\r\n");
      out.write("    	        passwdConfirm : $('#passwdConfirm').val(),\r\n");
      out.write("    	        birth : $('#birth').val(),\r\n");
      out.write("    	        phone :$('#phone').val(),\r\n");
      out.write("    	        email : $('#email').val()\r\n");
      out.write("    	    }\r\n");
      out.write("    	\r\n");
      out.write("    	$.ajax({\r\n");
      out.write("    		url : '/user/add.do',\r\n");
      out.write("    		type :'post',\r\n");
      out.write("    		dataType : 'json',\r\n");
      out.write("    		data :param\r\n");
      out.write("    	}).done(function(res){\r\n");
      out.write("    		if(res.resultCode === 200){\r\n");
      out.write("    			alert('신규 사용자가 등록되었습니다.')\r\n");
      out.write("    		}else{\r\n");
      out.write("    			\r\n");
      out.write("    			alert('신규 사용자가 등록실패하였습니다.')\r\n");
      out.write("    		}\r\n");
      out.write("    		location.href=\"/user/login.do\"\r\n");
      out.write("    	}).fail(function(xhr, status, error) {\r\n");
      out.write("    		if(xhr.status === 500){\r\n");
      out.write("    			const res = JSON.parse(xhr.responseText);\r\n");
      out.write("    			alert(res.msg[0]);\r\n");
      out.write("    		}\r\n");
      out.write("    	  });\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  const goList=(e)=>{\r\n");
      out.write("	  location.href='/board/list2.do';\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  function init(){\r\n");
      out.write("    // 콜백함수를 부여할 때 매개변수를 전달해야할 경우가 있음.\r\n");
      out.write("    // 그럴경우  콜백자리에 바로 함수(매개변수); 라고 적으면 안됨\r\n");
      out.write("    // Ex)  joinBtn.addEventListener('click', go(data));\r\n");
      out.write("    // go(); 라고 하면 실행의 의미를 가짐 \r\n");
      out.write("    // 이럴 경우 콜백함수를 만들고 그 안에서 실행할 함수와 매개변수 처리해야함 \r\n");
      out.write("    // ex) joinBtn.addEventListener('click', function(){  goJoin();  });\r\n");
      out.write("    const joinBtn = document.querySelector('#joinBtn');\r\n");
      out.write("    const cancelBtn  = document.querySelector('#cancelBtn')\r\n");
      out.write("    joinBtn.addEventListener('click', (e) => goJoin(e));\r\n");
      out.write("    cancelBtn.addEventListener('click', (e) => goList(e));\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  //jquery 시작함수 \r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    init();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
