/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-28 05:33:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/header/header.jsp", Long.valueOf(1756357281970L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1755754927504L));
    _jspx_dependants.put("jar:file:/C:/nahyun.shin/web_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/spring-master/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel =\"stylesheet\" href=\"/webjars/bootstrap/5.3.1/css/bootstrap.min.css\"/>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("    display : flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin-top: 10vh;\r\n");
      out.write("    height:90vh;\r\n");
      out.write("    \r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("  .contents{\r\n");
      out.write("  	 width: 80%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(".data-list{\r\n");
      out.write("    width : 100%;\r\n");
      out.write("    height : 600px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("        *{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-container{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            background-color: black;\r\n");
      out.write("            height: 80px;\r\n");
      out.write("            line-height: 20px;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .nav-menu{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link{\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 1rem 1.5rem;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .nav-link:hover{ \r\n");
      out.write("            background-color: #eaeaea;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .nav-link.active{\r\n");
      out.write("            background-color: rgb(116, 137, 206);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div class=\"nav-container\">\r\n");
      out.write("				<ul class=\"nav-menu\">\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"/board/list.do\"\r\n");
      out.write("						data-page=\"naver\" class=\"nav-link\">게시판1</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"/board/list2.do\"\r\n");
      out.write("						data-page=\"daum\" class=\"nav-link\">게시판2</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"/board/userList.do\"\r\n");
      out.write("						data-page=\"daum\" class=\"nav-link\">사용자 게시판</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul class=\"nav-menu\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("	\r\n");
      out.write("						\r\n");
      out.write("						</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function move(site){\r\n");
      out.write("        const menuLinks = document.querySelectorAll('.nav-link');\r\n");
      out.write("\r\n");
      out.write("        menuLinks.forEach( link => {\r\n");
      out.write("            link.classList.remove('active');\r\n");
      out.write("            id = link.getAttribute('data-page');\r\n");
      out.write("            if(site === id) {\r\n");
      out.write("                link.classList.add('active');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	 <main class=\"container\">\r\n");
      out.write("     <section class=\"contents\">\r\n");
      out.write("        <header class=\"text-center\">\r\n");
      out.write("             <h2>사용자 리스트 </h2>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <section class=\"data-list\">\r\n");
      out.write("           <input type=\"hidden\" id=\"currentPage\" name=\"currentPage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("           <table class='table'>\r\n");
      out.write("              <colgroup>\r\n");
      out.write("              	<col style=\"width:30%\"/>\r\n");
      out.write("              	<col style=\"width:70%\"/>\r\n");
      out.write("               \r\n");
      out.write("              </colgroup>\r\n");
      out.write("              <thead class=\"table-dark text-center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>ID</th>\r\n");
      out.write("                  <th>유저이름</th>\r\n");
      out.write("                  \r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody id=\"boardBody\">\r\n");
      out.write("              </tbody>\r\n");
      out.write("           </table>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"page\">\r\n");
      out.write("	        <nav aria-label=\"Page navigation example\">\r\n");
      out.write("			  <ul class=\"pagination justify-content-center\"  id=\"page\">\r\n");
      out.write("			     \r\n");
      out.write("			  </ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("        </section>\r\n");
      out.write("     </section>\r\n");
      out.write("   </main>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"/webjars/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/webjars/bootstrap/5.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("   function movePage(pageNum) {\r\n");
      out.write("	   //페이지 번호 업데이트 \r\n");
      out.write("	   $('#currentPage').val(pageNum);\r\n");
      out.write("	   getBoardData();\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //서버에 데이터 요청 \r\n");
      out.write("   function getBoardData(){\r\n");
      out.write("	   //비동기로 서버에 데이터 요청\r\n");
      out.write("	   $.ajax(\r\n");
      out.write("			  {\r\n");
      out.write("				  \r\n");
      out.write("		 		url : '/board/list/data.do',  //요청 경로 \r\n");
      out.write("		 		type : 'get',        //전송 방식\r\n");
      out.write("		 		dataType : 'json',   //돌려받을 데이터 타입,\r\n");
      out.write("		 		data : {\r\n");
      out.write("		 			currentPage : $('#currentPage').val()\r\n");
      out.write("		 		}\r\n");
      out.write(" 	   		}\r\n");
      out.write("	   ).done(function(res){\r\n");
      out.write("		   \r\n");
      out.write("		   drawTable(res);\r\n");
      out.write("		   \r\n");
      out.write("	   }).fail(function(xhr, status, error){\r\n");
      out.write("		  alert(error); \r\n");
      out.write("	   });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function  drawTable(data) {\r\n");
      out.write("	   \r\n");
      out.write("	   const tbody = $('#boardBody');\r\n");
      out.write("	   \r\n");
      out.write("	   //비워\r\n");
      out.write("	   tbody.empty();\r\n");
      out.write("	   \r\n");
      out.write("	   //테이블 만들기 \r\n");
      out.write("	   $.each(data.dataList, function(index, obj){\r\n");
      out.write("		  const tr = $('<tr></tr>'); \r\n");
      out.write("		  const link = $('<a></a>');\r\n");
      out.write("		  link.attr('href', 'javascript:void(0);');\r\n");
      out.write("		  //jquery에서 객체에 이벤트 바인딩 하는 방법 \r\n");
      out.write("		  link.on('click', ()=> goDteail(obj.brdId) );\r\n");
      out.write("		  \r\n");
      out.write("		  tr.append(makeTD('', obj.brdId));\r\n");
      out.write("		  tr.append(makeTD('', link.append(obj.title)) );\r\n");
      out.write("		  tr.append(makeTD('', obj.writer));\r\n");
      out.write("		  tr.append(makeTD('', obj.readCount));\r\n");
      out.write("		  tr.append(makeTD('', obj.likeCount));\r\n");
      out.write("		  tr.append(makeTD('', obj.modifiedDate));\r\n");
      out.write("		  \r\n");
      out.write("		  tbody.append(tr);\r\n");
      out.write("	   });\r\n");
      out.write("	   \r\n");
      out.write("	   const page = $('#page');\r\n");
      out.write("	   page.empty();\r\n");
      out.write("	   page.append(data.pageHTML);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function  makeTD(className,  contents){\r\n");
      out.write("	   const td = $('<td></td>');\r\n");
      out.write("	   td.addClass(className);\r\n");
      out.write("	   td.append(contents);\r\n");
      out.write("	   \r\n");
      out.write("	   return td;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   const goWrite = () => {\r\n");
      out.write("	   location.href = '/board/form.do';\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   //시작함수\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("	\r\n");
      out.write("	   getBoardData();\r\n");
      out.write("	   \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   const goDteail = (brdId) =>{\r\n");
      out.write("	   const currentPage = $('#currentPage').val();\r\n");
      out.write("	   location.href = '/board/detail.do?brdId=' + brdId +\"&currentPage=\" + currentPage;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/header/header.jsp(66,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("					<a href=\"/user/login.do\"\r\n");
        out.write("						data-page=\"register\" class=\"nav-link\">로그인</a>\r\n");
        out.write("					");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/header/header.jsp(70,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("						<p style=\"color:white\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("님 환영합니다.</p>\r\n");
        out.write("						<span style=\"color: white;\"><a href=\"/logout.do\">로그아웃</a></span>\r\n");
        out.write("					");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
